[package]
name = "hydro-host"
version = "0.1.0"
edition = "2021"

[dependencies]
hydro-eigenda.workspace = true
hydro-oracle.workspace = true
hydro-proofs.workspace = true

# Kona
kona-preimage = { workspace = true, features = ["std"] }
kona-proof = { workspace = true, features = ["std"] }
kona-providers-alloy.workspace = true
kona-std-fpvm.workspace = true
kona-genesis.workspace = true
kona-client.workspace = true
kona-host.workspace = true
kona-cli.workspace = true

# Alloy
alloy-rlp.workspace = true
alloy-provider = { workspace = true, features = ["ipc", "ws", "reqwest"] }
alloy-primitives = { workspace = true, features = ["map"] }

# Op Alloy
op-alloy-network.workspace = true

# Misc
reqwest = { workspace = true, features = ["json"] }
async-trait.workspace = true
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env"] }
