[package]
name = "hydro-client"
version = "0.1.0"
edition = "2021"

[dependencies]
hydro-eigenda.workspace = true
hydro-oracle.workspace = true

kona-preimage.workspace = true
kona-proof.workspace = true
kona-driver.workspace = true
kona-executor.workspace = true
kona-client.workspace = true
kona-std-fpvm.workspace = true
kona-std-fpvm-proc.workspace = true

alloy-primitives.workspace = true
alloy-consensus.workspace = true

tracing.workspace = true
cfg-if.workspace = true

[features]
default = ["client-tracing"]
client-tracing = ["kona-std-fpvm/tracing"]

[[bin]]
name = "hydro"
path = "src/hydro.rs"